// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGkz85ZtXX-RbmOZrnqyMjKIg1KzWubmU',
    appId: '1:582047631572:web:ca1475c85d6848d8209341',
    messagingSenderId: '582047631572',
    projectId: 'myfitnessapp-c0001',
    authDomain: 'myfitnessapp-c0001.firebaseapp.com',
    storageBucket: 'myfitnessapp-c0001.firebasestorage.app',
    measurementId: 'G-XPVQ4VBL3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy42IsLi2xaysD_JU6e568cc_y082qx90',
    appId: '1:582047631572:android:4da0681c9b755385209341',
    messagingSenderId: '582047631572',
    projectId: 'myfitnessapp-c0001',
    storageBucket: 'myfitnessapp-c0001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd2BpP9wriip5p0fkCNOdXaTL3DTcTqvc',
    appId: '1:582047631572:ios:cd950371a27ed2e1209341',
    messagingSenderId: '582047631572',
    projectId: 'myfitnessapp-c0001',
    storageBucket: 'myfitnessapp-c0001.firebasestorage.app',
    iosBundleId: 'com.example.myFitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd2BpP9wriip5p0fkCNOdXaTL3DTcTqvc',
    appId: '1:582047631572:ios:cd950371a27ed2e1209341',
    messagingSenderId: '582047631572',
    projectId: 'myfitnessapp-c0001',
    storageBucket: 'myfitnessapp-c0001.firebasestorage.app',
    iosBundleId: 'com.example.myFitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGkz85ZtXX-RbmOZrnqyMjKIg1KzWubmU',
    appId: '1:582047631572:web:3c75d61fd31d766b209341',
    messagingSenderId: '582047631572',
    projectId: 'myfitnessapp-c0001',
    authDomain: 'myfitnessapp-c0001.firebaseapp.com',
    storageBucket: 'myfitnessapp-c0001.firebasestorage.app',
    measurementId: 'G-CDMLG4JFHB',
  );
}
